#define BUZZER 9

#define DISPLAY_CE 10
#define DISPLAY_IN 11
#define DISPLAY_RS 12
#define DISPLAY_CLK 13
#define DISPLAY_RST 8

#define GYRO_SCL 16
#define GYRO_SDA 17

#define EMITTER_LEFT_HALF 2
#define EMITTER_RIGHT_HALF 3

#define IR_LEFT_ANGLE 19
#define IR_LEFT_FRONT 20

#define IR_RIGHT_ANGLE 22
#define IR_RIGHT_FRONT 21

#define MOTOR_FRONT_RIGHT_PWM 4
#define MOTOR_BACK_RIGHT_PWM  5

#define MOTOR_FRONT_LEFT_PWM 6
#define MOTOR_BACK_LEFT_PWM 7

#define MOTOR_LEFT_IN_1 24
#define MOTOR_LEFT_IN_2 26
#define MOTOR_RIGHT_IN_1 25
#define MOTOR_RIGHT_IN_2 27

#define ENCODER_FRONT_RIGHT_A 14
#define ENCODER_FRONT_RIGHT_B 15

#define ENCODER_BACK_RIGHT_A 29
#define ENCODER_BACK_RIGHT_B 28

#define ENCODER_FRONT_LEFT_A 30
#define ENCODER_FRONT_LEFT_B 31

#define ENCODER_BACK_LEFT_A 32
#define ENCODER_BACK_LEFT_B 33

#define BUTTON_1 18
#define BUTTON_2 23

#define MOTOR_VEL_PID_P 200
#define MOTOR_VEL_PID_I 0
#define MOTOR_VEL_PID_D 0
#define MOTOR_VEL_PID_F 255

#define MAX_VELOCITY 0.0058

#define ENCODER_TICKS_PER_WHEEL_ROTATION 360
#define WHEEL_TRACK 68.72
#define WHEEL_DIAMETER 24.2

#define DISPLAY_LENGTH 4